services:
  client:
    build:
      context: ../..  # Monorepo root relative to this compose file
      dockerfile: apps/client/Dockerfile
      args:
        VITE_BASE_URL: /api # API will be proxied by Nginx
    container_name: ecommerce_client
    ports:
      - "80:80" # Standard HTTP port for client
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - ecommerce_network

  server:
    build:
      context: ../.. # Monorepo root
      dockerfile: apps/server/Dockerfile
    container_name: ecommerce_server
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-ecommercedb}
      POCKETBASE_URL: http://pocketbase:8090
    ports:
      - "4000:4000" # Optional: Only needed if accessing server directly
    depends_on:
      postgres:
        condition: service_healthy
      pocketbase:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - ecommerce_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:4000/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:16-alpine
    container_name: ecommerce_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-ecommercedb}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Expose if you need to connect from host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-ecommercedb}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - ecommerce_network

  pocketbase:
    image: spectado/pocketbase:latest
    container_name: ecommerce_pocketbase
    command: serve --http="0.0.0.0:8090"
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/pb_data
    restart: unless-stopped
    networks:
      - ecommerce_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:8090/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  pgdata:
  pb_data:

networks:
  ecommerce_network:
    driver: bridge