version: '3.8'

services:
  frontend:
    image: YOUR_DOCKER_USERNAME/vite-express-ecom-frontend:latest
    restart: always
    networks:
      - ecom-net

  backend:
    image: YOUR_DOCKER_USERNAME/vite-express-ecom-backend:latest
    restart: always
    env_file: .env.prod
    networks:
      - ecom-net
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ecom-net
    depends_on:
      - frontend

  postgres:
    image: postgres:16
    env_file: .env.prod
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - ecom-net

  redis:
    image: redis:7
    networks:
      - ecom-net

networks:
  ecom-net:
    driver: bridge

volumes:
  pg_data: